#### IN this notebook, we will build Multi-class classification for the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) using Convolution Neural Networks (CNN). 

In [52]:
### Loading the mnist dataset in keras

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D
from keras import backend as b

In [84]:
## Split the data between train and test
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [90]:
x_test.shape

(10000, 28, 28, 1)

In [91]:
x_train

array([[[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]],

        ...,

        [[0],
         [0],
         [0],
         ...,
         [0],


In [86]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [87]:
## input image dimensions
img_rows,img_cols=28,28

In [92]:
### Reshape the image

if b.image_data_format() =='channel_first':
    x_train = x_train.reshape(x_train.shape[0],1,img_rows,img_cols)
    x_test = x_test.reshape(x_test.shape[0],1,img_rows,img_cols)
    input_shape=(1,img_rows,img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0],img_rows,img_cols,1)
    x_test = x_test.reshape(x_test.shape[0],img_rows,img_cols,1)
    input_shape=(img_rows,img_cols,1)
        

In [93]:
x_train =x_train.astype('float32')
x_test =x_test.astype('float32')
x_train/=255
x_test/=255
print('x_train shape',x_train.shape)

x_train shape (60000, 28, 28, 1)


In [95]:
x_test

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [72]:
### As target variable having 10 classes, we need to convert to binary class matrix
num_classes=10
y_train = keras.utils.to_categorical(y_train,10) 
y_test = keras.utils.to_categorical(y_test,10)

In [73]:
y_train[3]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [74]:
#### Model Initialization

model=Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation= 'relu',input_shape=input_shape))## Input layer
model.add(Conv2D(64,kernel_size=(3,3),activation= 'relu')) ### Convolution layer 2
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))
model.add(Flatten()) #### Image converted to faltten numbers,This will feed as input to the FNN
model.add(Dense(128,activation='relu'))   
model.add(Dense(num_classes,activation='softmax'))          

In [75]:
#### Model compilation

model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [76]:
model.fit(x_train,y_train,epochs=3,batch_size=128,verbose=1,validation_data=(x_test,y_test))
score =model.evaluate(x_test,y_test,verbose=0)
print("test_loss",score[0])
print("test_accuracy",score[1])

Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 923s 15ms/step - loss: 0.1929 - accuracy: 0.9420 - val_loss: 0.0463 - val_accuracy: 0.9840
Epoch 2/3
60000/60000 [==============================] - 835s 14ms/step - loss: 0.0494 - accuracy: 0.9848 - val_loss: 0.0371 - val_accuracy: 0.9883
Epoch 3/3
60000/60000 [==============================] - 862s 14ms/step - loss: 0.0334 - accuracy: 0.9888 - val_loss: 0.0369 - val_accuracy: 0.9871
test_loss 0.03689230942735448
test_accuracy 0.9871000051498413


In [78]:
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
dropout_3 (Dropout)          (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dense_6 (Dense)              (None, 10)               

In [79]:
#### Predict the test data
test_pred = model.predict(x_test)

In [80]:
import numpy as np


In [81]:
#### view the first 20 predicted images 

np.argmax(test_pred,axis=1)[:25]

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6,
       6, 5, 4], dtype=int64)

In [83]:
### Lets compare how many mismatches
(np.argmax(test_pred,axis=1)!=np.argmax(y_test,axis=1)).sum()



129